-- MySQL Script generated by MySQL Workbench
-- Sat Jul 19 13:08:24 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema viaje
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema viaje
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `viaje` DEFAULT CHARACTER SET utf8 ;
USE `viaje` ;

-- -----------------------------------------------------
-- Table `viaje`.`Turistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viaje`.`Turistas` (
  `CodigoTuristas` INT NOT NULL AUTO_INCREMENT,
  `NombreTurista` VARCHAR(45) NULL,
  `ApellidosTurista` VARCHAR(45) NULL,
  `DireccionTurista` VARCHAR(80) NULL,
  `TelefonoTurista` VARCHAR(10) NULL,
  PRIMARY KEY (`CodigoTuristas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viaje`.`Hoteles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viaje`.`Hoteles` (
  `CodigoHotel` INT NOT NULL AUTO_INCREMENT,
  `NombreHotel` VARCHAR(45) NULL,
  `DireccionHotel` VARCHAR(45) NULL,
  `CiudadHotel` VARCHAR(45) NULL,
  `TelefonoHotel` VARCHAR(10) NULL,
  `PlazasHotel` INT NULL,
  PRIMARY KEY (`CodigoHotel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viaje`.`Estancias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viaje`.`Estancias` (
  `CodigoEstancia` INT NOT NULL AUTO_INCREMENT,
  `Pension` VARCHAR(45) NULL,
  `FechaEntrada` DATE NULL,
  `FechaSalida` DATE NULL,
  `Hoteles_CodigoHotel` INT NOT NULL,
  PRIMARY KEY (`CodigoEstancia`, `Hoteles_CodigoHotel`),
  INDEX `fk_Estancias_Hoteles1_idx` (`Hoteles_CodigoHotel` ASC),
  CONSTRAINT `fk_Estancias_Hoteles1`
    FOREIGN KEY (`Hoteles_CodigoHotel`)
    REFERENCES `viaje`.`Hoteles` (`CodigoHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viaje`.`Sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viaje`.`Sucursales` (
  `CodigoSucursal` INT NOT NULL AUTO_INCREMENT,
  `DireccionSucursal` VARCHAR(45) NULL,
  `TelefonoSucursal` VARCHAR(10) NULL,
  PRIMARY KEY (`CodigoSucursal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viaje`.`ViajesContratados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viaje`.`ViajesContratados` (
  `CodigoViaje` INT NOT NULL AUTO_INCREMENT,
  `Turistas_CodigoTuristas` INT NOT NULL,
  `Sucursales_CodigoSucursal` INT NOT NULL,
  `Estancias_CodigoEstancia` INT NOT NULL,
  PRIMARY KEY (`CodigoViaje`, `Turistas_CodigoTuristas`, `Sucursales_CodigoSucursal`, `Estancias_CodigoEstancia`),
  INDEX `fk_ViajesContratados_Turistas1_idx` (`Turistas_CodigoTuristas` ASC),
  INDEX `fk_ViajesContratados_Estancias1_idx` (`Estancias_CodigoEstancia` ASC),
  INDEX `fk_ViajesContratados_Sucursales1_idx` (`Sucursales_CodigoSucursal` ASC),
  CONSTRAINT `fk_ViajesContratados_Turistas1`
    FOREIGN KEY (`Turistas_CodigoTuristas`)
    REFERENCES `viaje`.`Turistas` (`CodigoTuristas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ViajesContratados_Estancias1`
    FOREIGN KEY (`Estancias_CodigoEstancia`)
    REFERENCES `viaje`.`Estancias` (`CodigoEstancia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ViajesContratados_Sucursales1`
    FOREIGN KEY (`Sucursales_CodigoSucursal`)
    REFERENCES `viaje`.`Sucursales` (`CodigoSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viaje`.`Vuelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viaje`.`Vuelos` (
  `NumeroVuelos` INT NOT NULL AUTO_INCREMENT,
  `FechaVuelo` DATE NULL,
  `HoraVuelo` DATE NULL,
  `OrigenVuelo` VARCHAR(45) NULL,
  `DestinoVuelo` VARCHAR(45) NULL,
  `PlazasTotales` INT NULL,
  `PlazasTurista` INT NULL,
  PRIMARY KEY (`NumeroVuelos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `viaje`.`VuelosTurista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viaje`.`VuelosTurista` (
  `CodigoVuelo` INT NOT NULL AUTO_INCREMENT,
  `Clase` VARCHAR(20) NULL,
  `Vuelos_NumeroVuelos` INT NOT NULL,
  `ViajesContratados_CodigoViaje` INT NOT NULL,
  PRIMARY KEY (`CodigoVuelo`, `Vuelos_NumeroVuelos`, `ViajesContratados_CodigoViaje`),
  INDEX `fk_VuelosTurista_ViajesContratados_idx` (`ViajesContratados_CodigoViaje` ASC),
  INDEX `fk_VuelosTurista_Vuelos1_idx` (`Vuelos_NumeroVuelos` ASC),
  CONSTRAINT `fk_VuelosTurista_ViajesContratados`
    FOREIGN KEY (`ViajesContratados_CodigoViaje`)
    REFERENCES `viaje`.`ViajesContratados` (`CodigoViaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VuelosTurista_Vuelos1`
    FOREIGN KEY (`Vuelos_NumeroVuelos`)
    REFERENCES `viaje`.`Vuelos` (`NumeroVuelos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
